#!/usr/bin/env node

// PreCompact hook: Save structured session state before compaction
// This is the #1 anti-drift mechanism for long sessions
const fs = require('fs');
const path = require('path');

const BEHAVIOR_PATH = path.join(process.env.HOME, '.claude', 'behavior.json');
const HANDOFF_DIR = path.join(process.env.HOME, '.claude', 'handoff');
const HANDOFF_PATH = path.join(HANDOFF_DIR, 'HANDOFF.md');

function main() {
  let behavior;
  try {
    behavior = JSON.parse(fs.readFileSync(BEHAVIOR_PATH, 'utf8'));
  } catch {
    behavior = {};
  }

  // Gather state
  const parts = ['# Session Handoff (auto-generated by PreCompact hook)', ''];
  parts.push(`**Timestamp**: ${new Date().toISOString()}`);
  parts.push(`**Tool calls this session**: ${behavior.tool_call_count || 'unknown'}`);
  parts.push(`**Mode**: autonomy=${behavior.autonomy || 'autonomous'}`);
  parts.push(`**Active domain**: ${behavior.active_domain || 'none'}`);
  parts.push('');

  // Active toggles
  const toggles = behavior.toggles || {};
  const active = Object.entries(toggles).filter(([, v]) => v).map(([k]) => k);
  if (active.length) {
    parts.push(`**Active toggles**: ${active.join(', ')}`);
  }

  // Git state
  try {
    const { execFileSync } = require('child_process');
    const branch = execFileSync('git', ['branch', '--show-current'], { encoding: 'utf8', timeout: 5000 }).trim();
    const diffFiles = execFileSync('git', ['diff', '--name-only', 'HEAD'], { encoding: 'utf8', timeout: 5000 }).trim();
    const untrackedCount = execFileSync('git', ['ls-files', '--others', '--exclude-standard'], { encoding: 'utf8', timeout: 5000 }).trim().split('\n').filter(Boolean).length;

    parts.push('');
    parts.push('## Git State');
    parts.push(`- Branch: ${branch}`);
    if (diffFiles) {
      parts.push(`- Modified files: ${diffFiles.split('\n').join(', ')}`);
    }
    if (untrackedCount > 0) {
      parts.push(`- Untracked files: ${untrackedCount}`);
    }

    // Recent commits
    const recentCommits = execFileSync('git', ['log', '--oneline', '-5'], { encoding: 'utf8', timeout: 5000 }).trim();
    if (recentCommits) {
      parts.push(`- Recent commits:\n${recentCommits.split('\n').map(c => `  - ${c}`).join('\n')}`);
    }
  } catch {}

  // Ensure handoff directory exists
  if (!fs.existsSync(HANDOFF_DIR)) {
    fs.mkdirSync(HANDOFF_DIR, { recursive: true });
  }

  const handoffContent = parts.join('\n');
  fs.writeFileSync(HANDOFF_PATH, handoffContent);
  console.log('Handoff state saved to HANDOFF.md');

  // Write structured JSON for autopilot consumption
  try {
    const { execFileSync } = require('child_process');
    const AUTOPILOT_DIR = path.join(process.env.HOME, '.claude', 'autopilot');
    const AUTOPILOT_JSON = path.join(AUTOPILOT_DIR, 'last-session.json');

    // Extract summary: use the handoff content minus the header line
    const summaryLines = handoffContent.split('\n').filter(l => l && !l.startsWith('# Session Handoff'));
    const summary = summaryLines.slice(0, 5).join('; ').replace(/\*\*/g, '');

    // Git state for JSON
    let activeBranch = null;
    let uncommittedChanges = false;
    let recentCommits = [];
    try {
      activeBranch = execFileSync('git', ['branch', '--show-current'], { encoding: 'utf8', timeout: 5000 }).trim();
      const statusOutput = execFileSync('git', ['status', '--porcelain'], { encoding: 'utf8', timeout: 5000 }).trim();
      uncommittedChanges = statusOutput.length > 0;
      const logOutput = execFileSync('git', ['log', '--format=%s', '-3'], { encoding: 'utf8', timeout: 5000 }).trim();
      recentCommits = logOutput ? logOutput.split('\n') : [];
    } catch {}

    // Extract pending work: lines that suggest unfinished items
    const pendingIndicators = /TODO|FIXME|WIP|pending|unfinished|blocked|DEFERRED|in.progress|remaining/i;
    const pendingWork = handoffContent.split('\n')
      .filter(l => pendingIndicators.test(l))
      .map(l => l.replace(/^[\s\-*]+/, '').trim())
      .filter(Boolean);

    const sessionJson = {
      session_id: null,
      timestamp: new Date().toISOString(),
      task_id: null,
      summary: summary,
      state: {
        working_directory: process.cwd(),
        active_branch: activeBranch,
        uncommitted_changes: uncommittedChanges,
        recent_commits: recentCommits
      },
      pending_work: pendingWork
    };

    if (!fs.existsSync(AUTOPILOT_DIR)) {
      fs.mkdirSync(AUTOPILOT_DIR, { recursive: true });
    }
    fs.writeFileSync(AUTOPILOT_JSON, JSON.stringify(sessionJson, null, 2));
    console.log('Session JSON saved to autopilot/last-session.json');
  } catch (jsonErr) {
    // Don't break existing hook if autopilot JSON fails
    console.error('Failed to write autopilot JSON:', jsonErr.message);
  }
}

try {
  main();
} catch (err) {
  try {
    const fs2 = require('fs');
    const path2 = require('path');
    fs2.appendFileSync(path2.join(process.env.HOME, '.claude', 'hook-errors.log'),
      `[${new Date().toISOString()}] [precompact-handoff.js] ${err?.stack || err}\n`);
  } catch {}
}
